#!/bin/bash
#
# an ascii fetch heavily based on ufetch : https://gitlab.com/jschx/ufetch

## INFO
os_release_file="/etc/os-release"
os=$(grep -m 1 -oP '(?<=NAME=").*(?=")' "$os_release_file")

host="$(hostname)"
kernel="$(uname -sr)"
shell="$(basename "${SHELL}")"
dir=$(dirname "$0")
desktop_env=$(echo $XDG_CURRENT_DESKTOP)
desktop_env="${desktop_env#*: }"
desktop_env="${desktop_env%%:*}"
cpu_model=$(lscpu | awk -F': ' '/Model name/ {print $2}' | xargs)

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold 2> /dev/null)"
	black="$(tput setaf 0 2> /dev/null)"
	red="$(tput setaf 1 2> /dev/null)"
	green="$(tput setaf 2 2> /dev/null)"
	yellow="$(tput setaf 3 2> /dev/null)"
	blue="$(tput setaf 4 2> /dev/null)"
	magenta="$(tput setaf 5 2> /dev/null)"
	cyan="$(tput setaf 6 2> /dev/null)"
	white="$(tput setaf 7 2> /dev/null)"
	reset="$(tput sgr0 2> /dev/null)"
fi

# you can change these
lc="${reset}${bold}${blue}"        # labels
nc="${reset}${bold}${red}"        # user and hostname
ic="${reset}"                       # info
c0="${reset}${bold}${green}"        # first color
c1="${reset}${green}"               # second color

show_help() {
    echo "Usage: afetch [OPTIONAL FILE] [-h | --help]"
    echo
    echo "Displays ASCII art from the specified file."
    echo "If no file is provided, a fetch with no art will be shown."
    echo
    echo "Optional Arguments:"
    echo "  FILE              	Name of the file containing ASCII art."
    echo "  -h, --help        	Show help information."
    echo
    echo "Examples:"
    echo "  ./afetch              # Displays default ASCII art"
    echo "  ./afetch artwork  	# Displays ASCII art from artwork.txt"
}


# Check if -h or --help is passed as the first argument
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

## OUTPUT
if [ $# -ne 0 ]
  then
	echo
	cat $dir/$1
fi

cat << EOF
${nc} ${USER}${ic}@${nc}${host}${reset}
${lc} OS:        ${ic}${os}${reset}
${lc} CPU:       ${ic}${cpu_model}${reset}
${lc} KERNEL:    ${ic}${kernel}${reset}
${lc} SHELL:     ${ic}${shell}${reset}
${lc} DE:        ${ic}${desktop_env}${reset}
EOF
echo
